name: Process Server List Issue
on:
  issues:
    types: [opened, closed]

permissions:
  issues: write
  contents: write

jobs:
  process_issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Ensure labels exist
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh label create "等待审核" --color FFFFFF --description "等待管理员审核"
        gh label create "通过审核" --color 00FF00 --description "管理员通过审核"
      continue-on-error: true

    - name: Add "等待审核" label
      if: github.event.action == 'opened'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh issue edit ${{ github.event.issue.number }} --add-label "等待审核"

    - name: Remove "等待审核" label and add "通过审核"
      if: github.event.action == 'closed'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh issue edit ${{ github.event.issue.number }} --remove-label "等待审核" --add-label "通过审核"

    - name: Fetch issue data
      if: github.event.action == 'closed'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ISSUE_NUMBER=${{ github.event.issue.number }}
        ISSUE_DATA=$(gh issue view $ISSUE_NUMBER --json body -q .body)
        ICON_LINK=$(echo "$ISSUE_DATA" | jq -r 'match("(?<=图标链接（服务器图标）：\\*\\*\\K[^\\*]+").string')
        SERVER_TITLE=$(echo "$ISSUE_DATA" | jq -r 'match("(?<=服务器标题：\\*\\*\\K[^\\*]+").string')
        SERVER_VERSION=$(echo "$ISSUE_DATA" | jq -r 'match("(?<=服务器版本（如：Java 1.21/Bedrock 1.21）：\\*\\*\\K[^\\*]+").string')
        WEBSITE_QQ_LINK=$(echo "$ISSUE_DATA" | jq -r 'match("(?<=官网/QQ 群链接：\\*\\*\\K[^\\*]+").string')
        LINK_TITLE=$(echo "$ISSUE_DATA" | jq -r 'match("(?<=链接标题：\\*\\*\\K[^\\*]+").string')

        echo -e "\n\n  - icon:\n      src: $ICON_LINK\n    title: $SERVER_TITLE\n    details: 版本：$SERVER_VERSION | $SERVER_TITLE</br>example描述\n    link: $WEBSITE_QQ_LINK\n    linkText: $LINK_TITLE" >> docs/index.md
        sed -i '302s/$/\n/' docs/index.md

    - name: Commit changes
      if: github.event.action == 'closed'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add docs/index.md
        git commit -m "Update server list for issue #${ISSUE_NUMBER}"
        git push
